### ISSUE TITLE
You are a real hero!

### ISSUE THREAD

**Issue by heartical** [josxha/Oryon#8]
Thank you so much for this project! If you need help with anything, please contact me.

**Comment by josxha** [comment]
Thanks a lot for the message @heartical! ...and I'm very sorry for the late response.
This project is part of my evaluation process weather the ory services fit my use case.

I think both, OryAdmin and OrySelfService, probably need some more work and polishment done before they can be used in production. Althrough the biggest blocker is currently that the ory team hasn't released updates to its packages for .net in some time (see https://github.com/josxha/OryUI/issues/11). If you have an idea how to get some awareness to this it would be very appreciated. 

Because I'm a bit short in time, my plan is currently to implement new features (like pagination) when I require them.
But if you want to contribute: feature requests, bug reports or even pull requests are always welcome and appreciated. 👍🏼
